# Generated by Django 5.0.3 on 2024-06-14 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cikgu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nidn", models.CharField(max_length=20, verbose_name="Nidn")),
                (
                    "namadosen",
                    models.CharField(max_length=100, verbose_name="Nama Lengkap"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jurusan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kodejurusan", models.CharField(max_length=50, verbose_name="Kode")),
                (
                    "namajurusan",
                    models.CharField(max_length=150, verbose_name="Program Studi"),
                ),
                (
                    "jenjang",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("D3", "DIPLOMA-3"),
                            ("D4", "DIPLOMA-4"),
                            ("S1", "STRATA-1"),
                            ("S2", "STRATA-2"),
                            ("S3", "STRATA-3"),
                        ],
                        max_length=150,
                        null=True,
                        verbose_name="Jenjang",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="guru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nidn", models.CharField(max_length=20, verbose_name="Nidn")),
                (
                    "namadosen",
                    models.CharField(max_length=100, verbose_name="Nama Lengkap"),
                ),
                (
                    "jk",
                    models.CharField(
                        choices=[("L", "LAKI-LAKI"), ("P", "PEREMPUAN")],
                        max_length=50,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                ("tanggallahir", models.DateField(verbose_name="Tanggal Lahir")),
                ("alamat", models.TextField(verbose_name="Alamat")),
                (
                    "foto",
                    models.ImageField(upload_to="foto_dosen", verbose_name="Foto"),
                ),
                ("cv", models.FileField(upload_to="cv_dosen", verbose_name="cv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perkuliahan.jurusan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mahasiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nim", models.CharField(max_length=50, verbose_name="Nim")),
                (
                    "namalengkap",
                    models.CharField(max_length=150, verbose_name="Nama Lengkap"),
                ),
                (
                    "jk",
                    models.CharField(
                        choices=[("L", "LAKI-LAKI"), ("P", "PEREMPUAN")],
                        max_length=50,
                        verbose_name="Jenis Kelamin",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="contoh: admin@gmail.com",
                        max_length=254,
                        null=True,
                        verbose_name="E-Mail",
                    ),
                ),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perkuliahan.jurusan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matakuliah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kodemk",
                    models.CharField(max_length=100, verbose_name="Kode Matakuliah"),
                ),
                (
                    "namamk",
                    models.CharField(max_length=150, verbose_name="Nama Matakuliah"),
                ),
                ("semester", models.CharField(max_length=50, verbose_name="Semester")),
                ("sks", models.IntegerField(verbose_name="SKS")),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perkuliahan.jurusan",
                    ),
                ),
            ],
        ),
    ]
