# Generated by Django 5.0.3 on 2024-06-14 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perkuliahan", "0002_delete_cikgu_delete_guru"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dosen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nidn", models.CharField(max_length=20, verbose_name="Nidn")),
                (
                    "namadosen",
                    models.CharField(max_length=100, verbose_name="Nama Lengkap"),
                ),
                (
                    "gelar",
                    models.CharField(
                        help_text="contoh: S.KOM.,M.Kom",
                        max_length=30,
                        verbose_name="Gelar",
                    ),
                ),
                (
                    "tgllahir",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tanggal Lahir"
                    ),
                ),
                (
                    "templahir",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Tempat Lahir",
                    ),
                ),
                ("foto", models.ImageField(upload_to="foto_mhs", verbose_name="Foto")),
                ("cv", models.FileField(upload_to="cv_dosen", verbose_name="Cv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "jurusan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="perkuliahan.jurusan",
                        verbose_name="Program Studi",
                    ),
                ),
            ],
        ),
    ]
